# Generated by Django 5.2.14 on 2026-05-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingrecord',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='parkingrecord',
            name='parking_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parking_records', to='parking.parkingspot', verbose_name='Vaga'),
        ),
    ]
